version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8

    commands:
      - pip3 install awscli aws-sam-cli --upgrade
      - pip install -r ./requirements.txt

  build:
    commands:
      - sam build
      - sam package -t template.yml --s3-bucket $S3_BUCKET --output-template-file ./template-export.yml
      
artifacts:
  files:
    - template.yml
    - template-export.yml
