AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  AppId:
    Type: String

  Environment:
    Description: ambiente de execucao do servico
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod

Globals:
  Function:
    Runtime: python3.8
    MemorySize: 1024
    Timeout: 120
    Layers:
      - !Ref ScrapperLibrariesLayer
      - !Ref ScrapperCommonLayer

  Api:
    OpenApiVersion: 3.0.2
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Conditions:
  Prod: !Equals [ !Ref Environment, prod ]

Resources:
  ScrapperLibrariesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: bibliotecas externas.
      ContentUri: layers/libraries/app
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8
  
  ScrapperCommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: bibliotecas internas.
      ContentUri: layers/common
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8

  ScrapingFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ScrapingFn-${Environment}"
      CodeUri: src/api
      Handler: handler.handler
      Description: Scraping websites
      Events:
        Api:
          Type: Api
          Properties:
            Path: /v1
            Method: POST

  Chromium:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:339543757547:applications/Chromium
        SemanticVersion: 1.0.0